import string
import re
from datetime import datetime
from scrapy.spiders import Spider
from scrapy.selector import Selector
from offer.items import OfferItem

class OfferSpider(Spider):
    name = "offer" # Name of the spider, to be used when crawling
    allowed_domains = ["tesco.com"] # Where the spider is allowed to go

#    start_urls = [
##        "https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=0",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=100",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=200",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=300",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=400",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=500",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=600",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=700",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=800",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=900",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1000",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1100",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1200",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1300",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1400",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1500",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1600",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1700",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1800",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=1900",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=2000",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=2100",
#		"https://www.tesco.com/groceries/SpecialOffers/SpecialOfferList/default.aspx?promoType=alloffers&Nao=2200"
#    ]
"""
    start_urls = [
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=1",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=2",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=3",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=4",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=5",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=6",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=7",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=8",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=9",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=10",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=11",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=12",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=13",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=14",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=15",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=16",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=17",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=18",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=19",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=20",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=21",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=22",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=23",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=24",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=25",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=26",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=27",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=28",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=29",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=30",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=31",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=32",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=33",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=34",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=35",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=36",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=37",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=38",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=39",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=40",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=41",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=42",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=43",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=44",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=45",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=46",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=47",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=48",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=49",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=50",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=51",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=52",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=53",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=54",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=55",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=56",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=57",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=58",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=59",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=60",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=61",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=62",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=63",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=64",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=65",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=66",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=67",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=68",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=69",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=70",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=71",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=72",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=73",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=74",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=75",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=76",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=77",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=78",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=79",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=80",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=81",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=82",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=83",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=84",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=85",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=86",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=87",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=88",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=89",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=90",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=91",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=92",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=93",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=94",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=95",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=96",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=97",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=98",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=99",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=100",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=101",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=102",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=103",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=104",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=105",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=106",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=107",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=108",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=109",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=110",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=111",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=112",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=113",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=114",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=115",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=116",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=117",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=118",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=119",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=120",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=121",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=122",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=123",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=124",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=125",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=126",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=127",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=128",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=129",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=130",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=131",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=132",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=133",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=134",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=135",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=136",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=137",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=138",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=139",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=140",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=141",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=142",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=143",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=144",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=145",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=146",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=147",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=148",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=149",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=150",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=151",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=152",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=153",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=154",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=155",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=156",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=157",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=158",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=159",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=160",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=161",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=162",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=163",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=164",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=165",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=166",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=167",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=168",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=169",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=170",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=171",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=172",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=173",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=174",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=175",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=176",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=177",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=178",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=179",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=180",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=181",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=182",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=183",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=184",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=185",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=186",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=187",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=188",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=189",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=190",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=191",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=192",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=193",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=194",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=195",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=196",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=197",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=198",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=199",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=200",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=201",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=202",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=203",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=204",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=205",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=206",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=207",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=208",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=209",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=210",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=211",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=212",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=213",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=214",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=215",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=216",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=217",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=218",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=219",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=220",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=221",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=222",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=223",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=224",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=225",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=226",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=227",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=228",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=229",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=230",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=231",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=232",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=233",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=234",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=235",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=236",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=237",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=238",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=239",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=240",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=241",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=242",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=243",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=244",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=245",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=246",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=247",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=248",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=249",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=250",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=251",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=252",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=253",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=254",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=255",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=256",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=257",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=258",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=259",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=260",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=261",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=262",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=263",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=264",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=265",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=266",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=267",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=268",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=269",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=270",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=271",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=272",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=273",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=274",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=275",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=276",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=277",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=278",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=279",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=280",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=281",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=282",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=283",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=284",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=285",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=286",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=287",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=288",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=289",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=290",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=291",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=292",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=293",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=294",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=295",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=296",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=297",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=298",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=299",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=300",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=301",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=302",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=303",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=304",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=305",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=306",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=307",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=308",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=309",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=310",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=311",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=312",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=313",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=314",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=315",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=316",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=317",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=318",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=319",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=320",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=321",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=322",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=323",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=324",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=325",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=326",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=327",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=328",
        "https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=329"
    ]
"""

    start_urls = [
        'https://www.tesco.com/groceries/en-GB/promotions/alloffers?page=%d' % (n) for n in range(1,330)
    ]    
	
    def parse(self, response):
        hxs = Selector(response) # The XPath selector

        # XPath Tags
        productlist_tag = '//div[@class="product-lists"]//ul[@class="product-list grid"]/li'
        product_id_tag = './/div[@class="product-tile--wrapper"]//div[@class="tile-content"]/a/@href'
        product_imgsrc_tag = './/img/@src'
        product_desc_tag = './/div[@class="product-details--wrapper"]//a/text()'
        offer_desc_tag = './/li[@class="product-promotion"]//span[@class="offer-text"]/text()'
        validity_desc_tag = './/li[@class="product-promotion"]//span[@class="dates"]/text()'
        offertags = hxs.xpath(productlist_tag)
        ###

        offers = []
        for offertag in offertags:
            offer = OfferItem()
            offer['productid'] = offertag.xpath(product_id_tag).extract()[0].replace("/groceries/en-GB/products/","")
            if offertag.xpath(product_imgsrc_tag).extract():
                offer['imgsrc225'] = offertag.xpath(product_imgsrc_tag).extract()[0]
                offer['imgsrc110'] = offertag.xpath(product_imgsrc_tag).extract()[0].replace('225x225','110x110')
                offer['imgsrc90'] = offertag.xpath(product_imgsrc_tag).extract()[0].replace('225x225','90x90')
                offer['imgsrc540'] = offertag.xpath(product_imgsrc_tag).extract()[0].replace('225x225','540x540')
            else:
                offer['imgsrc90'] = ""
                offer['imgsrc540'] = ""
                offer['imgsrc110'] = ""
                offer['imgsrc225'] = ""
            if offertag.xpath().extract(product_desc_tag):
                offer['productdesc'] = offertag.xpath(product_desc_tag).extract()[0]
            else:
                offer['productdesc'] = ""
            if offertag.xpath(offer_desc_tag).extract():
                offer['offerdesc'] = offertag.xpath(offer_desc_tag).extract()[0]
            else:
                offer['offerdesc'] = ""
            if offertag.xpath().extract(validity_desc_tag):
                offer['validitydesc'] = offertag.xpath(validity_desc_tag).extract()[0]
            else:
                offer['validitydesc'] = ""
            offers.append(offer)
        return offers # To be changed later